export enum StatusPedidoEnum {
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
  PENDENTE = 'PENDENTE',
  EM_SEPARACAO = 'EM_SEPARACAO',
  ENVIADO = 'ENVIADO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}
